import 'dart:convert';
import 'dart:io';

import 'package:brand_icons/src/catalog/brand_catalog.dart';
import 'package:brand_icons/src/core/brand_query.dart';
import 'package:brand_icons/src/matching/name_normalizer.dart';
import 'package:brand_icons/src/providers/bundled_icon_provider.dart';
import 'package:flutter_test/flutter_test.dart';

/// Proves this port scores identically to the Swift reference.
///
/// `golden-corpus.json` is generated by the Swift package and copied here verbatim. If the scores
/// drift, the ports have silently stopped agreeing about what "Netflix" means, and this is the
/// only thing that would notice.
void main() {
  final corpus =
      jsonDecode(File('test/fixtures/golden-corpus.json').readAsStringSync()) as List<dynamic>;
  final catalog = BrandCatalog.parse(File('assets/brand_marks.json').readAsStringSync());

  test('normalisation matches the reference', () {
    for (final row in corpus) {
      final query = row['query'] as String;
      expect(NameNormalizer.key(query), row['normalizedKey'], reason: 'key for "$query"');
      expect(
        NameNormalizer.brandTokens(query),
        (row['brandTokens'] as List<dynamic>).cast<String>(),
        reason: 'tokens for "$query"',
      );
    }
  });

  test('scores match the reference', () async {
    final provider = BundledIconProvider(catalog);
    for (final row in corpus) {
      final query = row['query'] as String;
      final expected = (row['candidates'] as List<dynamic>).cast<Map<String, dynamic>>();
      final found = (await provider.candidates(BrandQuery(query))).take(5).toList();

      expect(
        found.map((candidate) => candidate.slug).toList(),
        expected.map((candidate) => candidate['slug']).toList(),
        reason: 'candidates for "$query"',
      );

      for (var index = 0; index < expected.length; index++) {
        expect(
          found[index].confidence,
          closeTo(expected[index]['confidence'] as num, 1e-4),
          reason: 'confidence for "$query" / ${expected[index]['slug']}',
        );
      }
    }
  });

  test('the catalogue is the version the corpus was generated from', () {
    expect(catalog.sourceVersion, '16.28.0');
    expect(catalog.marks.length, 4770);
  });
}
